# docker-compose.yml
services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.production

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    env_file:
      - .env.development
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json