# docker-compose.yml
services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
      - "443:3443"
    env_file:
      - .env.production
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "3443:3443"
    env_file:
      - .env.development
    volumes:
      - ./src:/app/src
      - ./certificates:/app/certificates
      - ./package.json:/app/package.json